- name: Install GoLang
  ansible.builtin.dnf:
    name: golang
    state: installed


- name: Load App Prerequisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Download Application Dependencies
  ansible.builtin.shell:
    name: "{{ item }}"
  loop:
    - go mod init dispatch
    - go get
    - go build
  args:
    chdir: /app




- name: Load SystemD setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml