- name: Install Python
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
    loop:
      - python3
      - gcc
      - python3-devel

- name: Load app prerequisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml


- name: Download Application Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Load systemd
  ansible.builtin.include_tasks:
    file: systemd_setup.yml
